version: "3"

services:
  selenium-services:
    image: selenium/standalone-chrome:4.0.0-alpha-7-20201119
    container_name: selenium_container
    ports:
      - "4444:4444"
    logging:
      driver: none

  test-runner-services:
    build:
      context: .
      dockerfile: .
    image: test_runner_image
    container_name: test_runner_container
    network_mode: "host"
